### ISSUE TITLE
插件报错

### ISSUE THREAD

**Issue by PackageInstaller** [shinianj/zhenxun_plugin_personalshop#5]
直接git clone下载的
![Screenshot_20230120_091150](https://user-images.githubusercontent.com/80018096/213596839-42b0cc9a-2d38-4ae7-b3a7-8195bf600847.png)

插件是加载成功了的，报错如下
01-20 09:14:06 [ERROR] apscheduler | Job "_ (trigger: interval[0:00:30], next run at: 2023-01-20 09:14:36 CST)" raised an exception
Traceback (most recent call last):
  File "/home/Neko/QQBot/zhenxun_bot/bot.py", line 21, in <module>
    nonebot.run()
  File "/home/Neko/.cache/pypoetry/virtualenvs/zhenxun-bot-PzlhPUjk-py3.10/lib/python3.10/site-packages/nonebot/__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "/home/Neko/.cache/pypoetry/virtualenvs/zhenxun-bot-PzlhPUjk-py3.10/lib/python3.10/site-packages/nonebot/drivers/fastapi.py", line 172, in run
    uvicorn.run(
  File "/home/Neko/.cache/pypoetry/virtualenvs/zhenxun-bot-PzlhPUjk-py3.10/lib/python3.10/site-packages/uvicorn/main.py", line 569, in run
    server.run()
  File "/home/Neko/.cache/pypoetry/virtualenvs/zhenxun-bot-PzlhPUjk-py3.10/lib/python3.10/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
> File "/home/Neko/.cache/pypoetry/virtualenvs/zhenxun-bot-PzlhPUjk-py3.10/lib/python3.10/site-packages/apscheduler/executors/base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
  File "/home/Neko/QQBot/zhenxun_bot/extensive_plugin/zhenxun_plugin_personalshop/creat_shop.py", line 1049, in _
    good_lst,owner = await PersonalGoods.get_group_goods(g)
  File "/home/Neko/QQBot/zhenxun_bot/extensive_plugin/zhenxun_plugin_personalshop/_personal_goodsinfo.py", line 224, in get_group_goods
    await cls.create(
  File "/home/Neko/.cache/pypoetry/virtualenvs/zhenxun-bot-PzlhPUjk-py3.10/lib/python3.10/site-packages/gino/crud.py", line 444, in _create_without_instance
    return await cls(**values)._create(bind=bind, timeout=timeout)
  File "/home/Neko/.cache/pypoetry/virtualenvs/zhenxun-bot-PzlhPUjk-py3.10/lib/python3.10/site-packages/gino/crud.py", line 477, in _create
    row = await bind.first(q)
  File "/home/Neko/.cache/pypoetry/virtualenvs/zhenxun-bot-PzlhPUjk-py3.10/lib/python3.10/site-packages/gino/engine.py", line 748, in first
    return await conn.first(clause, *multiparams, **params)
  File "/home/Neko/.cache/pypoetry/virtualenvs/zhenxun-bot-PzlhPUjk-py3.10/lib/python3.10/site-packages/gino/engine.py", line 328, in first
    return await result.execute(one=True)
  File "/home/Neko/.cache/pypoetry/virtualenvs/zhenxun-bot-PzlhPUjk-py3.10/lib/python3.10/site-packages/gino/dialects/base.py", line 214, in execute
    rows = await cursor.async_execute(
  File "/home/Neko/.cache/pypoetry/virtualenvs/zhenxun-bot-PzlhPUjk-py3.10/lib/python3.10/site-packages/gino/dialects/asyncpg.py", line 184, in async_execute
    result, stmt = await getattr(conn, "_do_execute")(query, executor, timeout)
  File "/home/Neko/.cache/pypoetry/virtualenvs/zhenxun-bot-PzlhPUjk-py3.10/lib/python3.10/site-packages/asyncpg/connection.py", line 1730, in _do_execute
    result = await executor(stmt, None)
  File "asyncpg/protocol/protocol.pyx", line 201, in bind_execute
asyncpg.exceptions.NotNullViolationError: null value in column "owner_qq" of relation "personal_goods" violates not-null constraint
DETAIL:  Failing row contains (29, null, 491222411, {}).
01-20 09:14:06 [ERROR] apscheduler | Job "_ (trigger: interval[0:00:30], next run at: 2023-01-20 09:14:36 CST)" raised an exception
Traceback (most recent call last):
  File "/home/Neko/QQBot/zhenxun_bot/bot.py", line 21, in <module>
    nonebot.run()
  File "/home/Neko/.cache/pypoetry/virtualenvs/zhenxun-bot-PzlhPUjk-py3.10/lib/python3.10/site-packages/nonebot/__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "/home/Neko/.cache/pypoetry/virtualenvs/zhenxun-bot-PzlhPUjk-py3.10/lib/python3.10/site-packages/nonebot/drivers/fastapi.py", line 172, in run
    uvicorn.run(
  File "/home/Neko/.cache/pypoetry/virtualenvs/zhenxun-bot-PzlhPUjk-py3.10/lib/python3.10/site-packages/uvicorn/main.py", line 569, in run
    server.run()
  File "/home/Neko/.cache/pypoetry/virtualenvs/zhenxun-bot-PzlhPUjk-py3.10/lib/python3.10/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
> File "/home/Neko/.cache/pypoetry/virtualenvs/zhenxun-bot-PzlhPUjk-py3.10/lib/python3.10/site-packages/apscheduler/executors/base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
  File "/home/Neko/QQBot/zhenxun_bot/extensive_plugin/zhenxun_plugin_personalshop/creat_shop.py", line 1009, in _
    good_lst,owner = await PersonalGoods.get_group_goods(g)
  File "/home/Neko/QQBot/zhenxun_bot/extensive_plugin/zhenxun_plugin_personalshop/_personal_goodsinfo.py", line 224, in get_group_goods
    await cls.create(
  File "/home/Neko/.cache/pypoetry/virtualenvs/zhenxun-bot-PzlhPUjk-py3.10/lib/python3.10/site-packages/gino/crud.py", line 444, in _create_without_instance
    return await cls(**values)._create(bind=bind, timeout=timeout)
  File "/home/Neko/.cache/pypoetry/virtualenvs/zhenxun-bot-PzlhPUjk-py3.10/lib/python3.10/site-packages/gino/crud.py", line 477, in _create
    row = await bind.first(q)
  File "/home/Neko/.cache/pypoetry/virtualenvs/zhenxun-bot-PzlhPUjk-py3.10/lib/python3.10/site-packages/gino/engine.py", line 748, in first
    return await conn.first(clause, *multiparams, **params)
  File "/home/Neko/.cache/pypoetry/virtualenvs/zhenxun-bot-PzlhPUjk-py3.10/lib/python3.10/site-packages/gino/engine.py", line 328, in first
    return await result.execute(one=True)
  File "/home/Neko/.cache/pypoetry/virtualenvs/zhenxun-bot-PzlhPUjk-py3.10/lib/python3.10/site-packages/gino/dialects/base.py", line 214, in execute
    rows = await cursor.async_execute(
  File "/home/Neko/.cache/pypoetry/virtualenvs/zhenxun-bot-PzlhPUjk-py3.10/lib/python3.10/site-packages/gino/dialects/asyncpg.py", line 184, in async_execute
    result, stmt = await getattr(conn, "_do_execute")(query, executor, timeout)
  File "/home/Neko/.cache/pypoetry/virtualenvs/zhenxun-bot-PzlhPUjk-py3.10/lib/python3.10/site-packages/asyncpg/connection.py", line 1730, in _do_execute
    result = await executor(stmt, None)
  File "asyncpg/protocol/protocol.pyx", line 201, in bind_execute
asyncpg.exceptions.NotNullViolationError: null value in column "owner_qq" of relation "personal_goods" violates not-null constraint
DETAIL:  Failing row contains (30, null, 491222411, {}).

**Comment by PackageInstaller** [comment]
报错的截图
![Screenshot_20230120_091547](https://user-images.githubusercontent.com/80018096/213597253-a359a96f-de1c-4f36-956a-b95ba50a29b9.png)
![Screenshot_20230120_091627](https://user-images.githubusercontent.com/80018096/213597297-a1107543-76ad-4b3a-8f77-75b841a4aee0.png)

**Comment by shinianj** [comment]
上架指令使用正常吗

**Comment by PackageInstaller** [comment]
能，但是一堆报错

**Comment by shinianj** [comment]
看看上架的报错

**Comment by PackageInstaller** [comment]
这个报错就是上面的，它隔一会就重复报错
真寻是最新的0.1.6.6
